services:
  # Backend Node.js
  - type: web
    name: backend-academia
    env: node
    region: oregon
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false

  # Frontend estático
  - type: web
    name: frontend-academia
    runtime: static
    rootDir: frontend
    buildCommand: ""
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /api/*
        destination: https://backend-academia.onrender.com/api/*

      - type: rewrite
        source: /*
        destination: /index.html